name: "WhoozyAction"
description: "Youtube counter and updater"
inputs:
  apiKey:
    description: "Your api Key"
    required: true
  videoId:
    description: "Your video Id"
    required: true
  videoTitle:
    description: "Title for the video. counter available : {watch} | {like} | {dislike} | {comment} | {subscribe}"
    required: false
    default: "THIS VIDEO HAS BEEN WATCHED {watch} TIMES"
  channelId:
    description: "Your channelId"
    required: false
  refreshToken:
    description: "Your refresh token"
    required: true
  clientSecret:
    description: "Your client secret"
    required: true
  redirectUri:
    description: "Your redirect uri"
    required: true
  clientId:
    description: "Your client id"
    required: true
outputs:
  log:
    description: "New video title"
runs:
  using: "node16"
  main: "dist/index.js"
